language: node_js
node_js:
  - "0.12"
  
before_install: 
  - gem install sass
  - npm install gulp
  - npm install gulp-scss-lint --save-dev

script:
  - npm install eslint
  - eslint *.js
  - gulp
  
notifications:
  email: false
