language: node_js
node_js:
  - "0.12"
  
before_install: 
  - gem install sass
  - gem install scss-lint 

script:
  - npm install eslint
  - eslint *.js
  - scss-lint
  
notifications:
  email: false
